### ISSUE TITLE
Code block styling in .epub version

### ISSUE THREAD

**Issue by chrisboyce** [skerkour/black-hat-rust#5] opened 2021-02-14 00:52 UTC
While the `pdf` and `mobi` formats show the code blocks in fixed-width font, it seems that the `epub` version does not (at least in [calibre](https://calibre-ebook.com/) 3.21). 

![image](https://user-images.githubusercontent.com/1100198/107865448-470ae200-6e1b-11eb-8e31-622c78c859b7.png)

**Comment by skerkour** [comment] 2021-02-14 10:55
Thank you for the feedback!
It's for sure a bug and not a feature and thus need to be fixed.

Do you have any idea about the root cause?

**Comment by chrisboyce** [comment] 2021-02-14 15:23
After poking at the source for a bit, I realized that the font it was using for code blocks (Courier New) was not a font I had installed locally. After installing it, the code blocks are showing up correctly. I'm not sure how much control you have over the content that's generated, but if the styling can be changed from 
```css
.c0 {
    color: #000000;
    font-weight: 400;
    text-decoration: none;
    vertical-align: baseline;
    font-size: 11pt;
    font-family: "Courier New";
    font-style: normal;
}
```

to 

```css
.c0 {
    color: #000000;
    font-weight: 400;
    text-decoration: none;
    vertical-align: baseline;
    font-size: 11pt;
    font-family: "Courier New", monospace; /* <---- added "monospace" fallback */
    font-style: normal;
}
```

then the ebook viewer should fall back on whichever monospace fonts they have locally if the named font isn't found.

**Comment by skerkour** [comment] 2021-02-17 21:22
Thank you very much for this extremely detailed report!
I'm currently working on it and it should be fixed by tomorrow.

**Comment by skerkour** [comment] 2021-02-18 12:20
Update:
I have hard time fixing it with Google Docs so I'm currently trying other publishing software.

**Comment by skerkour** [comment] 2021-02-18 19:00
Update:
Due to Google Docs awfulness I'm moving away from it to Markdown + [pandoc](https://pandoc.org). It will take some time but according to my tests it will solve the issue.

**Comment by skerkour** [comment] 2021-02-23 12:03
Fixed thanks to `pandoc`.

The output is not perfect yet, but with some work on the theme and template it will be awesome!

**Closed by skerkour** 2021-02-23 12:03 UTC
